Bug Fix #6 and Update to 1.1

diff --git a/rootfs/services/_parent/run b/rootfs/services/_parent/run
--- a/rootfs/services/_parent/run
+++ b/rootfs/services/_parent/run
@@ -21,6 +21,10 @@ s6-svc -u /services/rsyslogd && s6-svwait -u /services/rsyslogd
 s6-svc -u /services/unbound  && [ "$DISABLE_DNS_RESOLVER" = true ] || s6-svwait -u /services/unbound
 s6-svc -u /services/redis && s6-svwait -u /services/redis
 s6-svc -u /services/mariadb && s6-svwait -u /services/mariadb
+if ! wait_local_mariadb; then
+ logger -p mail.info "s6-supervise : failed to initialize database. System can't go further."
+ exit 1
+fi
 s6-svc -u /services/postfix  && s6-svwait -u /services/postfix
 s6-svc -u /services/dovecot
 s6-svc -u /services/rspamd
